sonar.projectKey=HelioGuilherme66_robotframework-SikuliLibrary
sonar.organization=helioguilherme66
sonar.host.url=https://sonarcloud.io
sonar.python.version=3.13
sonar.projectVersion=v2.0.6
sonar.sources=src/
sonar.java.binaries=target/classes/com/github/rainmanwy/robotframework/sikulilib
# sonar.tests=utest/
sonar.dynamicAnalysis=reuseReports
sonar.core.codeCoveragePlugin=cobertura
sonar.python.coverage.reportPaths=.coverage-reports/*coverage*.xml
sonar.python.xunit.skipDetails=true
sonar.scm.provider=git
