name: Sonar
on:
  push:
    branches:
      - master
      - develop
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update ubuntu
        run: sudo apt update -y
      - name: Install missing library
        run: sudo apt-get install libnotify4 libsdl1.2debian libsdl2.2 wxpython-tools -y
      - name: Install JDK
        run: |
             sudo apt install -y ca-certificates curl gnupg
             sudo mkdir -p /etc/apt/keyrings
             curl -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo gpg --dearmor -o /etc/apt/keyrings/adoptium.gpg
             echo "deb [signed-by=/etc/apt/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
             sudo apt update && sudo apt install -y temurin-24-jdk
             sudo echo "export JAVA_HOME=/usr/lib/jvm/temurin-24-jdk-amd64" > ${{ github.workspace }}/jdk24.sh
             sudo echo "export PATH=$JAVA_HOME/bin:$PATH" >> ${{ github.workspace }}/jdk24.sh
             sudo chmod a+x ${{ github.workspace }}/jdk24.sh
             sudo /bin/bash ${{ github.workspace }}/jdk24.sh
      - name: Install xorg
        run: sudo apt-get install -y xorg openbox
      - name: Install Xvfb
        run: sudo apt-get install xvfb -y
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install invoke and any other packages
        run: pip install coverage invoke pytest
      - name: Install SikuliLibrary dependencies
        run: |
             python -m pip install -U pip
             pip install robotframework
      - name: Run Xvfb
        run: Xvfb :1 -noreset &
      - name: Test Install SikuliLibrary
        run: |
             ./build.sh
             pip install robotframework
             pip install dist/robotframework_sikulilibrary-*.whl 
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarqube-scan-action@v8.0.0
        with:
          projectBaseDir: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DISPLAY: :1

